url: http://tecna.ime.usp.br
#baseurl: "/"

# Site settings
title: Tecna
email: carolinarvan@usp.br
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Kelly Rosa Braguetto
  pic: 1
  position: Professora do Departamento de Ciência da Computação
  social:
    - title: twitter-square
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: #

- name: Renata Wassermann
  pic: 2
  position: Professora do Departamento de Ciência da Computação
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Carolina Andrade
  pic: 3
  position: Estudante de Matemática Aplicada e Computacional
  social:
    - title: instagram
      url: https://www.instagram.com/carolinarvan/
    - title: facebook
      url: https://www.facebook.com/rvacarolina
    - title: linkedin
      url: https://www.linkedin.com/in/carolina-rv-andrade/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter-square
    url: http://twitter.com/
  - title: facebook-f
    url: http://facebook.com/
  - title: github
    url: http://github.com/
  - title: instagram
    url: http://instagram.com/

# Postal address (add as many lines as necessary)
address:
  - line: Rua do Matão 1010 - Cidade Universitária
  - line: Butantã, São Paulo

# Build settings
markdown: kramdown
permalink: pretty
